import { readFileSync } from "fs";

export type HTMLTemplateProps = {
    title?: string;
    content?: string;
    /**
     * path should relative to `src` directory if using `internal` css else path
     * should be relative `templates` directory
    */
    styleSheetPaths: string[],
    /**
     * @option internal - include css file with style tag as internal css
     * @option external - just include css file path using link tag 
    */
    linkCSS: "internal" | "external"
} 

export default function HTMLTemplate (
    { title, content, styleSheetPaths, linkCSS }: HTMLTemplateProps
) {
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title || 'Notes'}</title>
  ${ 
    linkCSS === "internal" ?
    styleSheetPaths.map(path=> `<style>${readFileSync(path, "utf-8")}</style>`) :
    styleSheetPaths.map(path=> `<link path="${path}" rel="stylesheet" />`)
  }
</head>
<body>
<!--- Generated by Mark Down Compiler -->
${content}
<!--- END Generated by Mark Down Compiler -->
</body>
</html>    
`
}
